version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crypto_trading
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./../backend
    container_name: crypto_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crypto_trading
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - crypto_network

  frontend:
    build: ./../frontend
    container_name: crypto_frontend
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"
    networks:
      - crypto_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:

networks:
  crypto_network:
